apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    force-restart: "true" 
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql://dbuser:dbpassword@database/dbname
          image: backend
          name: backend
          ports:
            - containerPort: 30002
            - containerPort: 5000
          resources: {}
          imagePullPolicy: Never
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    force-restart: "true" 
    io.kompose.service: backend
  name: backend
spec:
  type: NodePort
  ports:
    - name: "30002"
      port: 30002
      targetPort: 30002
      nodePort: 31002
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: backend
status:
  loadBalancer: {}
